# CD Workflows:
# Authenticate to AWS via OIDC
# Run terraform plan and apply only on main
# Enforce environment protection: Pull Request on main

name: Continuous Deployment

on:
  push:
    branches:
      - staging  # → auto-deploy to staging
      - main     # → protected, deploy to production with approval


permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
      url: https://ce09-avengers-urlshortener.sctp-sandbox.com

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::255945442255:role/github-actions-deploy
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Plan
        run: terraform plan -var-file=../env/dev.tfvars
        working-directory: infra

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=../env/dev.tfvars
        working-directory: infra
