# CI Workflows:
# Lint Python code
# Zip Lambda functions
# Run terraform fmt and terraform validate

name: Continuous Integration

on:
  push:
    branches: [staging]

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    environment:
      name: staging

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Lint Lambda Code
        run: |
          pip install flake8
          flake8 lambdas/

      # - name: Zip Lambda Functions
      #   run: |
      #     chmod +x scripts/zip_lambdas.sh
      #     ./scripts/zip_lambdas.sh

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Show Terraform Format Diff
        run: terraform fmt -diff -recursive
        working-directory: infra

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra
