
name: Destroy on Failure

on:
  workflow_run:
    workflows: ["Continuous Deployment"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  destroy-on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    name: Destroy Infrastructure on Failure
    runs-on: ubuntu-latest

    environment:
      name: staging

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::255945442255:role/github-actions-deploy
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file=../env/dev.tfvars
        working-directory: infra
